version: '3.8'

services:
  
  postgresql-b:
    container_name: postgresql-b-no-sharding
    image: postgres:16.0
    restart: always
    ports:
      - 15432:5432
    volumes:
      - ./data/b/:/var/lib/postgresql/data/
      - ./setup.sql:/sql_scripts/setup.sql
    environment:
      POSTGRES_PASSWORD: postgres

  postgresql-ui:
    image: dpage/pgadmin4:7.6
    ports: 
      - 15480:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
