version: '3.8'

services:
  
  postgresql-b:
    container_name: postgresql-b
    image: postgres:16.0
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/b/:/var/lib/postgresql/data/
      - ./setup-main.sql:/sql_scripts/setup.sql
    environment:
      POSTGRES_PASSWORD: postgres

  postgresql-b1:
    container_name: postgresql-b1
    image: postgres:16.0
    restart: always
    ports:
      - 6432:5432
    volumes:
      - ./data/b1/:/var/lib/postgresql/data/
      - ./setup-shard.sql:/sql_scripts/setup.sql
    environment:
      POSTGRES_PASSWORD: postgres

  postgresql-b2:
    container_name: postgresql-b2
    image: postgres:16.0
    restart: always
    ports:
      - 7432:5432
    volumes:
      - ./data/b2/:/var/lib/postgresql/data/
      - ./setup-shard.sql:/sql_scripts/setup.sql
    environment:
      POSTGRES_PASSWORD: postgres

  postgresql-ui:
    image: dpage/pgadmin4:7.6
    ports: 
      - 5480:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
